# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Need to support ruby 1.8
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

Style/LineLength:
  Max: 100

Style/MethodLength:
  Max: 20

StringLiterals:
  Enabled: false
