AllCops:
  RunRailsCops: true # always run the rails cops

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Need to support ruby 1.8
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

StringLiterals:
  Enabled: false

Metrics/ClassLength:
  Max: 200
